# Generated by Django 3.2.9 on 2021-11-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
